#!/usr/bin/env bash

percent_alert=20
alert_sound="/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga"
time=60

sleep 10
while true
do
    export DISPLAY=:0.0

    while read line
	do
		value=$(echo $line | sed 's/%//g' | cut -d " " -f 2)
		key=$(echo $line | sed 's/%//g' | cut -d ":" -f 1)

		if [ $key = 'state' ]
		then
			bat_state=$value
		else
			bat_percent=$value
		fi
	done < <(upower -i `upower -e | grep BAT` | grep -E "percentage|state")


	if [ $bat_state = 'discharging' ]; then
        if [ $bat_percent -le $percent_alert ]; then
            notify-send --urgency=CRITICAL "Battery Low" "Level: ${bat_percent}%" --icon=battery-caution-symbolic
            paplay $alert_sound
        fi
    fi

    sleep $time
done
